# Generated by Django 4.2.3 on 2023-09-21 08:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pybo", "0002_class_professor_student_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="student",
        ),
    ]
